language: csharp
mono: none
dotnet: 3.1.100
mono: none
install:
  - sudo apt-get install -qq dotnet-sdk-2.0.0
script:
  - dotnet restore ./Src/Lytrax.AFM/
  - dotnet build ./Src/Lytrax.AFM/
  - dotnet test ./Src/Lytrax.AFM/Lytrax.AFM.Tests/
